ARCH = x86
SUBARCH = stage3-i686
#SUBARCH = stage3-i486
CHROOT = $(PWD)/newroot_$(ARCH)
inroot := linux32 -B chroot $(CHROOT)
STAGE3TXT = latest-stage3-i686.txt
#STAGE3TXT = latest-stage3-i486.txt

CHOST=i686-pc-linux-gnu
# CFLAGS=-march=atom -O2 -fomit-frame-pointer -pipe -mssse3 -mfpmath=sse -mmovbe
# CFLAGS=-O2 -march=core2 -mtune=generic -fomit-frame-pointer -pipe -mssse3 -mfpmath=sse
CFLAGS=-O2 -march=i686 -mtune=generic -pipe

include Makefile.common
